version: '2.2'
services:
  sh:
    build:
      context: .
    volumes:
      - ./config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./config/phar.ini:/usr/local/etc/php/conf.d/phar.ini:ro
      - ./:/app
      - ./environments:/environments
      - ./compose:/compose
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:/root/.ssh
      - $HOME/.docker:/opt/docker/.docker
    environment:
      - 'PHP_IDE_CONFIG=serverName=Docker'
      - 'BLACKFIRE_CLIENT_ID'
      - 'BLACKFIRE_CLIENT_TOKEN'
    command: [ "sleep", "31536000" ]
