name: Kloud Build Docker images
on:
  release:
    types:
      - created
  push:
    branches: [ feature/github-actions-test-stacks ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev
    - name: Build the Docker images
      uses: gplanchat/github-action-kloud-build@master
      with:
        php-version: '7.4'
        application: 'orocommerce'
        application-version: '4.1'
        edition: 'enterprise'
        dbms: 'postgresql'
        with-blackfire: true
        with-xdebug: true

